### ISSUE TITLE
Latest versions seems to not centre the text? 

### ISSUE THREAD

**Issue by sevenbe8** [forrestkirby/counter-element#10]
Hi, love the extension but I can't see how to make the text centred since I've updated to the latest version. Is there a new setting for this other than the 'centre text'? 

New version
https://dsc.cloud/965274/Screen-Shot-2020-05-05-18-43-41.50.png

Old version 
https://dsc.cloud/965274/Screen-Shot-2020-05-05-18-44-13.98.png

Thank you! 
Regine

**Comment by forrestkirby** [comment]
Hi Regine,

the element should take into account what you have set at *Settings > General > Text Alignment*. Despite that, the `div` containing the number and text is always centered with respect to the element due to the class `uk-position-center`. The only change from version 2.0.0-beta.9 to 2.0.4 was [removing an invalid attribute](https://github.com/forrestkirby/counter-element/commit/822de4f6c18d12a6ee19afab690f68772cd1da89) which most browsers tolerate anyways. I couldn’t see a difference for the text alignment on my end. If you could provide more details on how to reproduce this issue or the layout JSON for YOOtheme Pro 2.0.9, I could further investigate the issue.

Kind regards
Thomas

**Comment by sevenbe8** [comment]
Thank you so much for getting back to me. 


Can I send you a login so you can have a look behind the scenes? For now, I’ve switched off the animated circle but they are nice so it would be good to have them back and the content centred. 


Kindest regards
Regine




  
  
  



Essence  | Brand Strategy and Design
26 College Hill, Sutton Coldfield B73 6HA



Mob 07940 564849 | www.essence-design.co.uk


Read our Blog
 | Find me on LinkedIn

**Comment by forrestkirby** [comment]
You can send me login details via an encrypted mail to ***. Alternatively, you can ask a new question in the [YOOtheme support forum](http://yootheme.com/support/ask). Note that another supporter might take the question before I see it, but you’re in good hands with any member of the support team.
