### ISSUE TITLE
Button not active

### ISSUE THREAD

**Issue by Henri002** [forrestkirby/counter-element#12]
Yootheme Pro 2.0.7 and the latest version of this software. (downloaded from GitHub)
The button is visible (but on the bottom op popup under label 'HERZOG-DUPONT'), icon named HD Counter. But the button is not clickable?

<img width="478" alt="Screenshot 2020-06-16 at 15 15 14" src="https://user-images.githubusercontent.com/67007358/84779076-36803e80-afe4-11ea-961f-de283224397a.png">

**Comment by forrestkirby** [comment]
Hi Henri002,

the latest version of this element which has been merged today is made for YOOtheme Pro 2.1.0. I would recommend you to update YOOtheme Pro to the latest version, too (but always first update the custom elements, then directly update YOOtheme Pro).

If you need an older version because you don’t want to update YOOtheme Pro for any reason, you can browse the commit history of this GitHub repo for older commits. For example, try [version 2.0.9](https://github.com/forrestkirby/counter-element/tree/9a35b75f32328f69e8c2366ee5d803a6875b4b49)

Best regards
Thomas

**Comment by Henri002** [comment]
THANKS, works like a charm!!!!!!
