### ISSUE TITLE
Can't Use Dynamic Number

### ISSUE THREAD

**Issue by mehdisabbagh** [forrestkirby/counter-element#9]
Awesome element and congratulations.
I only saw one issue. Because of the numerical input, we can't use module in the space to get dynamic numbers. Is there a way to solve that?
For example we want to get the number from a custom code or module that we have written, how can we do that?
I think you can remove the numerical input, and just use a text input in order to read the module snippet code.

**Comment by forrestkirby** [comment]
Hi msabbagh627,

thank you for your positive feedback!

The `number` field does work with the dynamic content option provided by YOOtheme Pro, i.e. you could map a custom field of the type `integer` to the `number` field.

It does indeed not allow you to enter text etc which is on purpose because it’s not possible to count up to text and would require to add error handling for inserting anything else than a number. And frankly, I don’t see a use case that requires to allow different types and compensates for introducing a possible source of error.

Nevertheless, you can easily change the type of the field to match your needs. Simply change [line 47 of the ´element.json`](https://github.com/forrestkirby/counter-element/blob/master/hd-counter/element.json#L47) from

`"type": "number",`

to

`"type": "text",`

or

`"type": "textarea",`

Regards
Thomas
